Feature/plugin input support
UST-QuAntiL/qhana-plugin-runner pull request #25
Opened 2022-06-17 17:21 UTC by krebsni

2022-06-23 11:26 UTC, buehlefs requested changes

2022-06-23 11:26 UTC, buehlefs commented on .gitignore
> +plugins/test_plugin.py
we could add e local_plugins folder to gitignore and default config of the plugin runner to allow easy development with local plugins.

2022-06-23 11:26 UTC, buehlefs commented on qhana_plugin_runner/api/util.py
> +        self.validators[0] = FileUrlValidator(
The FileUrlValidator also validates file:// urls which should not work in this case. Either adapt (and rename) the file URL validator to enable/disable file:// urls on demand or create a separate validator.

2022-06-23 11:26 UTC, buehlefs commented on qhana_plugin_runner/api/util.py
> +class PluginUrl(ma.fields.URL):
Remove todo comment above if solved in this PR

2022-06-23 11:26 UTC, buehlefs commented on qhana_plugin_runner/static/microfrontend.js
> +    console.log(data);
Remove debug outputs if functionality is working

2022-06-23 11:26 UTC, buehlefs commented on qhana_plugin_runner/static/microfrontend.js
> +            // TODO: request-plugin-url-info
This should be relatively easy to implement in this PR

2022-07-04 07:54 UTC, PhilWun requested changes

2022-07-13 14:34 UTC, buehlefs approved these changes
lgtm (aside from the unused import)

2022-07-15 08:41 UTC, merged