Feature/validation feedback
UST-QuAntiL/qhana-plugin-runner pull request #58
Opened 2022-12-02 12:24 UTC by krebsni

2022-12-02 13:05 UTC, buehlefs requested changes
I've only left comments for the first occurrence but please fix them all.

2022-12-02 13:05 UTC, buehlefs commented on qhana_plugin_runner/templates/simple_template.html
> +            {% if errors == {} and valid %}
```suggestion
            {% if not errors and valid %}
```

2022-12-02 13:05 UTC, buehlefs commented on qhana_plugin_runner/templates/simple_template.html
> +            <mat-icon aria-hidden="true" class="material-icon notranslate material-icons ng-star-inserted qhana-valid-icon">done</mat-icon>
This actually works? A better solution would be to inline the icon SVG. Also make sure that the valid indicator has at least some text that can be seen (and read by screenreaders) explaining what the green checkmark actually means.

2022-12-09 14:45 UTC, krebsni commented on plugins/pca.py
> +# Copyright 2021 QHAna plugin runner contributors.
Not sure must have somehow slipped in when pca was refactored into own folder... I just deleted it for now.

2022-12-09 15:01 UTC, buehlefs approved these changes

2022-12-09 15:01 UTC, buehlefs commented on qhana_plugin_runner/templates/simple_template.html
> +            <svg class="checkmark" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40"><path class="checkmark__check" fill="none" d="M14.1 27.2l7.1 7.2 16.7-16.8"/></svg>
Add source and license info in html comment

2022-12-23 15:02 UTC, merged